# Generated by Django 3.2.8 on 2021-10-05 15:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import fontawesome_5.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nomi')),
                ('slug', models.SlugField(verbose_name='Slug')),
                ('icon', fontawesome_5.fields.IconField(blank=True, max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55, verbose_name='Nomi')),
                ('desc', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='image')),
                ('old_price', models.PositiveIntegerField(blank=True, default=0, verbose_name='Eski narhi')),
                ('price', models.PositiveIntegerField(blank=True, default=0, verbose_name='Hozirgi narhi')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postlar', to='blog.category', verbose_name='katalog')),
            ],
        ),
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=50, verbose_name='Telefon')),
                ('adress', models.CharField(blank=True, max_length=50, verbose_name='adress')),
                ('card_number', models.PositiveIntegerField(default=0)),
                ('like_dislike', models.ManyToManyField(to='blog.Post')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Userdata', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
